export const heroDatas = [
    {
        offer: 'Limited Time Offer 30% Off',
        buttonText: 'Shop Now',
        description: 'Experience Pure Sound Your Headphones Awaits!',
        navigate: 'Explore More',
        image: '/headphone1.png'
    },
    {
        offer: 'Exclusive Deal 30% Off',
        buttonText: 'Order Now',
        description: 'Stay Ahead with Samsung - Smart, Sleek, and Built for Life',
        navigate: 'Learn More',
        image: '/samsung.png'
    },
    {
        offer: 'Hurry up only few lefts!',
        buttonText: 'Buy Now',
        description: "Blend Better, Live Healthier for Discoveries",
        navigate: 'Find More',
        image: '/blender1.png'
    },
]

export const popularProducts = [
    {
        name: 'One Plus AirPods Pro',
        description: 'One Plus AirPods Pro 2nd gen with Noise Cancellation',
        rating: 4.2,
        price: 203.65,
        image: '/airbud.png',
        favorite: false,
    },
    {
        name: 'BMW Racing Bicycle',
        description: 'BMW racing bike with the power to ride on heels',
        rating: 4.5,
        price: 628.55,
        image: '/bicycle.png',
        favorite: false,
    },
    {
        name: 'Apower Industrial Blender',
        description: 'The Apower Industrial blender blends anything that comes it way',
        rating: 3.4,
        price: 100.30,
        image: '/blender1.png',
        favorite: false,
    },
    {
        name: 'Sulero 3D Camera',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.7,
        price: 89.10,
        image: '/camera.png',
        favorite: false,
    },
    {
        name: 'NY Fashion Cap',
        description: 'NY Fashion Cap Gives the opportunity to live in the moment',
        rating: 4.6,
        price: 100.30,
        image: '/cap.png',
        favorite: false,
    },
    {
        name: 'Electric Cooker',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 3.4,
        price: 450.30,
        image: '/cooker.png',
        favorite: false,
    },
    {
        name: 'A1 Electric Bike',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.1,
        price: 906.00,
        image: '/electricBike.png',
        favorite: false,
    },
    {
        name: 'Beat Headphone',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 2.6,
        price: 72.34,
        image: '/headphone1.png',
        favorite: false,
    },
    {
        name: 'HP Genz Laptop',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.0,
        price: 132.04,
        image: '/laptop.png',
        favorite: false,
    },
    {
        name: 'Ps5 Gaming Console',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.7,
        price: 273.30,
        image: '/ps5.png',
        favorite: false,
    },
    // {
    //     name: 'Sulero 3D Camera',
    //     description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
    //     rating: 3.4,
    //     price: 100.30,
    //     image: '/blender1.png',
    //     favorite: false,
    // },
    // {
    //     name: 'Sulero 3D Camera',
    //     description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
    //     rating: 3.4,
    //     price: 100.30,
    //     image: '/blender1.png',
    //     favorite: false,
    // },
    // {
    //     name: 'Sulero 3D Camera',
    //     description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
    //     rating: 3.4,
    //     price: 100.30,
    //     image: '/blender1.png',
    //     favorite: false,
    // },
]
export const AllProducts = [
    {
        name: 'One Plus AirPods Pro',
        description: 'One Plus AirPods Pro 2nd gen with Noise Cancellation',
        rating: 4.2,
        price: 203.65,
        image: '/airbud.png',
        favorite: false,
    },
    {
        name: 'BMW Racing Bicycle',
        description: 'BMW racing bike with the power to ride on heels',
        rating: 4.5,
        price: 628.55,
        image: '/bicycle.png',
        favorite: false,
    },
    {
        name: 'Apower Industrial Blender',
        description: 'The Apower Industrial blender blends anything that comes it way',
        rating: 3.4,
        price: 100.30,
        image: '/blender1.png',
        favorite: false,
    },
    {
        name: 'Sulero 3D Camera',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.7,
        price: 89.10,
        image: '/camera.png',
        favorite: false,
    },
    {
        name: 'NY Fashion Cap',
        description: 'NY Fashion Cap Gives the opportunity to live in the moment',
        rating: 4.6,
        price: 100.30,
        image: '/cap.png',
        favorite: false,
    },
    {
        name: 'Electric Cooker',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 3.4,
        price: 450.30,
        image: '/cooker.png',
        favorite: false,
    },
    {
        name: 'A1 Electric Bike',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.1,
        price: 906.00,
        image: '/electricBike.png',
        favorite: false,
    },
    {
        name: 'Beat Headphone',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 2.6,
        price: 72.34,
        image: '/headphone1.png',
        favorite: false,
    },
    {
        name: 'HP Genz Laptop',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.0,
        price: 132.04,
        image: '/laptop.png',
        favorite: false,
    },
    {
        name: 'Ps5 Gaming Console',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.7,
        price: 273.30,
        image: '/ps5.png',
        favorite: false,
    },
    {
        name: 'Samsung S23 ultra',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating:4.5,
        price: 900.70,
        image: '/samsung.png',
        favorite: false,
    },
    {
        name: 'JB Sport Shoe',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 2.4,
        price: 500.30,
        image: '/shoe.png',
        favorite: false,
    },
    {
        name: 'S24 ultra Smartwatch',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.4,
        price: 120.00,
        image: '/smartwatch.png',
        favorite: false,
    },
    {
        name: 'One Plus AirPods Pro',
        description: 'One Plus AirPods Pro 2nd gen with Noise Cancellation',
        rating: 4.2,
        price: 203.65,
        image: '/airbud.png',
        favorite: false,
    },
    {
        name: 'BMW Racing Bicycle',
        description: 'BMW racing bike with the power to ride on heels',
        rating: 4.5,
        price: 628.55,
        image: '/bicycle.png',
        favorite: false,
    },
    {
        name: 'Apower Industrial Blender',
        description: 'The Apower Industrial blender blends anything that comes it way',
        rating: 3.4,
        price: 100.30,
        image: '/blender1.png',
        favorite: false,
    },
    {
        name: 'Sulero 3D Camera',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.7,
        price: 89.10,
        image: '/camera.png',
        favorite: false,
    },
    {
        name: 'NY Fashion Cap',
        description: 'NY Fashion Cap Gives the opportunity to live in the moment',
        rating: 4.6,
        price: 100.30,
        image: '/cap.png',
        favorite: false,
    },
    {
        name: 'Electric Cooker',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 3.4,
        price: 450.30,
        image: '/cooker.png',
        favorite: false,
    },
    {
        name: 'A1 Electric Bike',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.1,
        price: 906.00,
        image: '/electricBike.png',
        favorite: false,
    },
    {
        name: 'Beat Headphone',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 2.6,
        price: 72.34,
        image: '/headphone1.png',
        favorite: false,
    },
    {
        name: 'HP Genz Laptop',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.0,
        price: 132.04,
        image: '/laptop.png',
        favorite: false,
    },
    {
        name: 'Ps5 Gaming Console',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.7,
        price: 273.30,
        image: '/ps5.png',
        favorite: false,
    },
    {
        name: 'Samsung S23 ultra',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating:4.5,
        price: 900.70,
        image: '/samsung.png',
        favorite: false,
    },
    {
        name: 'JB Sport Shoe',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 2.4,
        price: 500.30,
        image: '/shoe.png',
        favorite: false,
    },
    {
        name: 'S24 ultra Smartwatch',
        description: 'The Sulero 3D Camera is used to capture unforgettable moment and display as if it is live',
        rating: 4.4,
        price: 120.00,
        image: '/smartwatch.png',
        favorite: false,
    },
]

export const FeaturedProducts = [
    {
        heading: 'Power in Every Pixel',
        desc: 'Shop the latest laptops for work, gaming and more',
        image: '/Featured1.png',
        bg: 'bg-gradient-to-t from-gray-400 to-gray-200'
    },
    {
        heading: 'Unparalleled Sound',
        desc: 'Experience crystal-clear audio with premium headphones.',
        image: '/Featured2.png',
        bg: 'bg-gradient-to-t from-gray-400 to-gray-100'
    },
    {
        heading: 'Stay Connected',
        desc: 'Compact and stylish earphones for every occassion',
        image: '/Featured3.png',
        bg: 'bg-gradient-to-t from-gray-400 to-gray-300'
    }
]